// Generated by CoffeeScript 1.8.0
(function() {
  var LiteTouch, Socket, assert;

  assert = require('chai').assert;

  LiteTouch = require('../litetouch');

  Socket = require('./socket');

  describe('Callback', function() {
    var litetouch, socket;
    litetouch = null;
    socket = null;
    beforeEach(function() {
      socket = new Socket();
      return litetouch = new LiteTouch(socket);
    });
    return it('should callback on acknowledge', function(done) {
      socket.output = 'R,RSACK,SIEVN\r';
      return litetouch.send('SIEVN', '7', function() {
        return done();
      });
    });
  });

}).call(this);
