// Generated by CoffeeScript 1.6.2
(function() {
  var EventEmitter, Socket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  Socket = (function(_super) {
    __extends(Socket, _super);

    function Socket() {
      this.output = null;
    }

    Socket.prototype.write = function(input) {
      this.input = input;
      if (this.output) {
        return this.emit('readable');
      }
    };

    Socket.prototype.read = function() {
      if (this.output) {
        return this.output;
      }
    };

    return Socket;

  })(EventEmitter);

  module.exports = Socket;

}).call(this);
